name: Build Windows Executable

on:
  push:
    branches:
      - main # 或您的主要分支名稱

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 或您使用的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller nornir_cli click nornir nornir-utils nornir-jinja2 nornir-netmiko netmiko nornir-scrapli scrapli scrapli-netconf scrapli-community nornir-napalm ttp nornir-netbox nornir-pyez nornir-f5 nornir-paramiko nornir-http nornir-pyxl nornir-netconf nornir-routeros tqdm  

    - name: Run PyInstaller
      run: pyinstaller --onefile --collect-all nornir_cli nornir_cli.py # 将 your_script_name.py 替换为您的脚本名称

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist # 将 your_script_name.exe 替换为您的可执行文件名
